project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler403, handler500
from django.urls import include, path

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

app_name = 'project'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('grades/', views.grades, name='grades'),
    path('contact/', views.contact, name='contact'),
    path('index/', views.index, name='index'),
    path('', include('users.urls',namespace='users')),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from operator import index
from django.contrib import admin
from django.urls import path
from users.views import about, contact, grades
from . views import HomeView, login_user, Profile, logout_user, sign_up, teacher_request, edit_profile
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse

app_name = 'users'

urlpatterns = [
    path('about/', about, name='about'),
    path('index/', index, name='index'),
    path('grades/', grades, name='grades'),
    path('contact/', contact, name='contact'),
    path('register', views.register, name="register"),
    path('login', login_user, name="login"),
    path('profile/', views.Profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('logout_user', logout_user, name="logout_user"),
    path('sign_up', sign_up, name="sign_up"),
    path('teacher_request/', teacher_request, name='teacher_request'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.CharField(max_length=200, blank=True, null=True)
    profile_pic = models.ImageField(default='default.png', upload_to = 'profile_pics')
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username + ' Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.profile_pic.path)
        if img.height >100 or img.width>100:
            output_size = (200,200)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

class edit_profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.CharField(max_length=200, blank=True, null=True)
    profile_pic = models.ImageField(default='default.png', upload_to = 'profile_pics')
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username + ' Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.profile_pic.path)
        if img.height >100 or img.width>100:
            output_size = (200,200)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

class Requests(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    phone = models.CharField(max_length=15)

    def __str__(self):
        return self.profile.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import Profile

class userUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']


class profileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =['bio','profile_pic']

users/views.py
from django.contrib.auth.decorators import login_required
from courses.models import Klasa
from users.forms import profileUpdateForm, userUpdateForm
from django.views.generic import TemplateView
from users.models import Profile as Pro
from users.models import Requests
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from project import settings
from django.core.mail import send_mail
from django.core.mail import EmailMessage

# Create your views here.
def HomeView(request):
    return render(request, "home.html")
    
def home(request):
    return render(request, "home.html")

def about(request):
    return render(request, "about.html")

def contact(request):
    return render(request, "contact.html")

def grades(request):
    return render(request, "grades.html")

def index(request):
    return render(request, "index.html")

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password==confirm_password:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'username already exists' )
                return redirect(register)
            
            if User.objects.filter(email=email):
                messages.error(request, "Email already registered!")
                return redirect('home')
            
            if len(username)>10:
                messages.error(request, "Username must be under 10 caharacters")

            if password != confirm_password:
                messages.error(request, "Passwords didn't match!")
            
            if not username.isalnum():
                messages.error(request, "Username must be Alpha-Numeric")
                return redirect('home')
            
            user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
            user.set_password(password)
            #user.is_staff=True
            user.save()

            messages.success(request, "Your Account has been successfully created. We have sent you a confirmation email, please confirm your email in order to activate your account")

            # Welcome Email

            subject = "Welcome to Maktab Login!!"
            message = f"Hello {first_name}!! \nWelcome to Maktab!! \nThank you for visiting our website.\nWe have also sent you a confirmation email, please confirm your email address in order to activate your account.\n\nThanking You\nMaktab"
            from_email = settings.EMAIL_HOST_USER
            to_list = [email]
            send_mail(subject, message, from_email, to_list, fail_silently=True)

            return redirect('login')
    else:
        return render(request, "register.html")
    
def login_user(request):

    if request.method == 'POST':
        username =request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            first_name = user.first_name
            return render(request, 'profile/profile.html', {'first_name': first_name})
        else:
            messages.error(request, 'Invalid Username or Password')
            return redirect('home')
     
    return render(request,"login.html")

@login_required
def Profile(request):
    user = request.user
    if request.method == 'POST':
        u_form = userUpdateForm(request.POST,instance=request.user)
        p_form = profileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account was successfully updated!')
            return redirect('users:Profile')
    else:
        u_form = userUpdateForm(instance=request.user)
        p_form = profileUpdateForm(instance=request.user.profile)

    context= {
        'u_form':u_form,
        'p_form':p_form,
        'user:':user
    }
    return render(request,'profile/profile.html',context)

@login_required
def edit_profile(request):
    print("edit_profile view called")  # Debug statement
    if request.method == 'POST':
        print("POST request detected")  # Debug statement
        u_form = userUpdateForm(request.POST, instance=request.user)
        p_form = profileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            print("Forms are valid")  # Debug statement
            u_form.save()
            p_form.save()
            return redirect('users:profile')
    else:
        print("GET request detected")  # Debug statement
        u_form = userUpdateForm(instance=request.user)
        p_form = profileUpdateForm(instance=request.user.profile)
    
    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    print(context) 
    return render(request, 'profile/edit_profile.html', context)


def teacher_request(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('e-mail')
        phone = request.POST.get('phone')
        prof = request.user.profile

        # Create the teacher request
        teacher_request = Requests(profile=prof, name=name, email=email, phone=phone)
        teacher_request.save()

        # Update profile to mark as teacher
        prof.is_teacher = True
        prof.save()
        
    
def logout_user(request):
    logout(request)
    messages.success(request, "Logged Out Successfully!")
    return redirect('home')

def sign_up(request):
    return render(request, "register.html")

users/templates/home.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="description" content="WebUni Education Template">
    <meta name="keywords" content="webuni, education, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Maktab</title>
    	<!-- Favicon -->
	  <link href="{% static 'webuni/img/favicon.png' %}" rel="shortcut icon"/>

    	<!-- Google Fonts -->
	  <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">
      
      <!--Stylesheets-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/sketchy/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <!-- As a heading -->
  <nav class="navbar" style="background-image: url('{% static 'img/homeback.png' %}'); background-size: cover; background-position: center; height: 400px;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'img/logo.png' %}" height="30" width="30" class="d-inline-block align-top" alt=""> MAKTAB</a>
    </div>
    <span class="slogan" style="margin-top: 20px;">
      <span class=" line display-1" style="color: white; padding: 100px;">INNOVATIVE</span><br>
      <span class=" line display-1" style="color: rgb(255, 217, 93); padding: 100px;">LEARNING</span><br>
    </span>
    <div class="container-fluid" style="margin-right: 750px; margin-left: 100px;">
      <a class ="nav-item nav-link" href="{% url 'home' %}" style="color: white;">Home</a>
      <a class ="nav-item nav-link" href="{% url 'about' %}" style="color: white;">About us</a>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white;">Courses</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'index' %}">Create</a>
          <a class="dropdown-item" href="{% static 'webuni/courses.html' %}">Discover</a>
        </div>
      </div>  
      <a class ="nav-item nav-link" href="{% url 'contact' %}" style="color: white;">Contact</a>
      <!-- Dropdown -->
      {% if request.user.is_authenticated %}
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white;">
         Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
          <a class="dropdown-item" href="{% url 'users:edit_profile' %}">Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href={% url 'users:logout_user' %}>Logout</a>
      </div>
    </div>
    {% else %}
    {% endif %}
  </div>

    </div>  
  </nav>
  
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>Message:</strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    </button>    
    <span aria-hidden="true">&times;</span>
  </div>
  {% endfor %}
  <div class="container-fluid">
    {% if request.user.is_authenticated %}
    <h6 class="text-center" style="color: black;">You are already logged in</h6>
    <div style="margin-left: 40%;">
      <a href={% url 'users:profile' %} type="button" class="btn btn-info btn-lg" style="border:grey;">Go To Profile</a>
      <a href={% url 'users:logout_user' %} type="button" class="btn btn-danger btn-lg">Log Out</a>
    </div>
  {% else %}
  <div style="padding-left: 90px; display: flex; justify-content: center; margin: 50px; padding: 10px;">
  <a href={% url 'users:register' %} type="button" class="text-center btn btn-danger navbar-btn" style="border-radius: 20px; padding: 15px 30px; font-size: 20px; margin-right: 10px;">SIGN UP</a>
  <a href={% url 'users:login' %} type="button" class="text-center btn btn-danger navbar-btn" style="border-radius: 20px; padding: 15px 30px; font-size: 20px; margin-left: 10px;">LOG IN</a>
  </div>
  <body>
    {% endif %}
      <!-- First Body -->

    <div class="container" style="display: flex; align-items: center;">
      <div class="row">
          <img src="{% static 'img/girl1.png' %}" alt="">
        </div>
        <div class="col-md-6">
          <h2 style="color:black; font-weight: bold;">ABOUT THIS APPLICATION</h2>
          <p style="color:black;">Maktab is your one-stop destination for personalized learning tailored to your academic journey. With Maktab, students can seamlessly navigate through a variety of school subjects, selecting their grade level and desired subjects to embark on an enriching learning experience.</p>
          <p style="color:black;">From mathematics to literature, science to history, Maktab offers a comprehensive array of courses aligned with the Uzbekistan curriculum. With just a few clicks, students can choose their grade and subject, unlocking a wealth of resources, interactive lessons, and practice exercises designed to enhance their understanding and mastery of key concepts.</p>
          <a href="{% url 'users:register' %}" class="btn btn-danger" style="border-radius: 20px; padding: 10px 30px; font-size: 20px;">START LEARNING TODAY</a>
        </div>
      </div>
    </div>

    <!-- ICONS -->

    <div class="icon-container" style="display: flex; justify-content: center; margin-top: 50px;">
      <div class="icon" style="color: black; text-align: center; margin: 0 50px;">
        <i class="fas fa-book" style="font-size: 48px;"></i>
        <h6 style="margin-top: 10px; color: rgb(236, 34, 34); font-weight: bold;">ENGLISH</h6>
      </div>
      <div class="icon" style="color: black; text-align: center; margin: 0 50px;">
        <i class="fa fa-calculator" style="font-size: 48px;"></i>
        <h6 style="margin-top: 10px; color: rgb(236, 34, 34); font-weight: bold;">MATH</h6>
      </div>
      <div class="icon" style="color: black; text-align: center; margin: 0 50px;">
        <i class="fas fa-flask" style="font-size: 48px;"></i>
        <h6 style="margin-top: 10px; color: rgb(236, 34, 34); font-weight: bold;">SCIENCE</h6>
      </div>
    </div>

    <!-- Second body -->

    <div class="container" style="display: flex; flex-direction: row-reverse; justify-content: space-between; align-items: center;">
      <div class="image" style="flex: 1;">
        <img src="{% static 'img/girl2.png' %}" style="max-width:100%; display: block;" alt="">
      </div>
      <div class="text" style="flex: 1; padding: 0 20px;">
        <h2 style="color:black; font-weight: bold;">GRADES</h2>
        <p style="color: black; font-weight: bold;">The first step to start learning on this website is by choosing your grade. The lessons and exercises will be categorized by your level in school.</p>
        <a href="{% url 'users:register' %}" class="btn btn-danger" style="border-radius: 20px; padding: 10px 30px; font-size: 20px;">CHOOSE YOUR GRADE</a>
      </div>
    </div>

     <!-- Third body -->

     <div class="container" style="display: flex; align-items: center; margin-bottom: 100px;">
      <div class="row" style="flex: 1;">
          <img src="{% static 'img/boy1.png' %}" alt="">
        </div>
        <div class="col-md-6">
          <h2 style="color:black; font-weight: bold;">COURSES & LESSONS</h2>
          <p style="color:black;">We have variety of courses and lessons you can choose from. Our lessons align with the lessons in your schools. This will be a great tool for you to improve your education.</p>
          <a href="{% url 'users:register' %}" class="btn btn-danger" style="border-radius: 20px; padding: 10px 30px; font-size: 20px;">START LEARNING TODAY</a>
        </div>
      </div>
    </div>

  </body>
  </div>
  <!-- Footer Section -->
  <div class="blockcode">
    <footer class="page-footer navbar shadow" style="background-color: #ffa841; color: white;">
      <div class="d-flex flex-column mx-auto py-5" style="width: 80%">
        <div class="d-flex flex-wrap justify-content-between">
            <div>
              <p class="my-3 line display-3" href="{% url 'users:register' %}" type="button">
              START LEARNING
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <p class="my-3 line display-3" style="color:rgb(245, 193, 60);">
                TODAY
                </p>
                  <span class="mt-4 ml-auto" style="margin-left: 600px;">
                    <button class="btn btn-flat p-2" style="color:white; background-color:transparent; border-color: transparent;">
                    <i class="fab fa-telegram fa-2x"></i>
                    </button>
                    <button class="btn btn-flat p-2" style="color:white; background-color:transparent; border-color: transparent;">
                      <i class="fab fa-facebook fa-2x"></i>
                    </button>
                    <button class="btn btn-flat p-2" style="color:white; background-color:transparent; border-color: transparent;">
                      <i class="fab fa-youtube fa-2x"></i>
                    </button>
                  </span>
              </div>
              <h6 class="mt-5">
                <i class="fas fa-envelope"></i> malika.butaboeva@gmail.com
              </h6>
            </div>
      </footer>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

users/templates/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/sketchy/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body id='bg' style="background-image: url('{%static '/img/background.jpg'%}');">
    <!-- As a heading -->
<nav class="navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'img/logo.png' %}" height="30" width="30" class="d-inline-block align-top" alt=""> MAKTAB</a>
    </div>
  </nav>
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  <strong>Message:</strong> {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  </button>    
  <span aria-hidden="true">&times;</span>
    </div>
  {% endfor %}

    {% if request.user.is_authenticated %}
    <p class="text-success">You are Logged In</p>
    <p class="text-success">Username : {{ request.user.username }}</p>
    <p class="text-info">First Name : {{ request.user.first_name }}</p>
    <p class="text-info">Last Name : {{ request.user.last_name }}</p>
    {% else %}
        <p></p>
    {% endif %}

    <div class="container-fluid">
        <form action="{% url "users:login" %}" method="POST">
          <h1 class="text-center" style="color: white;">Sign In</h1>
            {% csrf_token %}
            <div class="row mb-3">
              <label for="username" class="" style="color: white; font-size: 20px;">Username:</label><br>
              <div><br>
                <input name="username" type="text" class="form-control" id="username" Required>
              </div>
            </div>
            <div class="row mb-3">
              <label for="" class="" style="color: white; font-size: 20px;">Password:</label><br>
              <div class=""><br>
                <input name="password" type="password" class="form-control" id="" Required>
              </div>
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-danger" style="font-size: 20px;">LOG IN</button>
            </div> 
            <div>
            <a href={% url 'users:sign_up' %} type="button" class="text-center" style="color:white; padding: 5%;"><h6 ><u>Sign Up</u></h6></a>
            </div>
          </form>
    </div>
  </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

users/templates/register.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/sketchy/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body id='bg' style="background-image: url('{%static '/img/background.jpg'%}');">
    <!-- As a heading -->
<nav class="navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'img/logo.png' %}" height="30" width="30" class="d-inline-block align-top" alt=""> MAKTAB</a>
    </div>
  </nav>
  <!-- Display messages -->
  <div class="container-fluid">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message:</strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}

  <div class="container-fluid">
        <form action="{% url 'users:register' %}" method="POST">
          <h1 style="color: white;">Sign Up</h1>
            {% csrf_token %}
            <div class="row mb-3">
              <label for="first_name" class="form-label" style="color: white; font-size: 20px;">First Name:</label>
              <input name= "first_name" type="text" class="form-control" id="first_name" Required>
            </div>
            <div class="row mb-3">
                <label for="last_name" class="form-label" style="color: white; font-size: 20px;">Last Name:</label>
                <input name= "last_name" type="text" class="form-control" id="last_name" Required>
              </div>
              <div class="row mb-3">
                <label for="email" class="form-label" style="color: white; font-size: 20px;">Email:</label>
                <input name= "email" type="email" class="form-control" id="email" Required>
              </div>
              <div class="row mb-3">
                <label for="username" class="form-label" style="color: white; font-size: 20px;">Username:</label>
                <input name= "username" type="text" class="form-control" id="username" Required>
              </div>
            <div class="row mb-3">
              <label for="password" class="form-label" style="color: white; font-size: 20px;">Password:</label>
              <input name= "password" type="password" class="form-control" id="password" Required>
            </div>
            <div class="row mb-3">
                <label for="confirm_password" class="form-label" style="color: white; font-size: 20px;">Confirm Password:</label>
                <input name= "confirm_password" type="password" class="form-control" id="confirm_password" Required>
              </div>
            <div>
              <button type="submit" class="btn btn-danger" style="font-size: 20px;">Sign Up</button> 
              <a href={% url 'users:login' %} type="button" style="color:white; padding: 5%;"><u>Log in</u></a>
            </div>
          </form>
          <div class="form-group">
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{messages}}
            </div>
            {% endfor %}
          </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>